name: Print Hello World

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x run.sh

      - name: Print Hello World
        run: ./run.sh
